version: "3"
services:
  db:
    image: postgres:latest
    container_name: ph-postgres-db-ph
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: BazaProjekt

  adminer:
    image: adminer
    container_name: ph-adminer-ph
    restart: always
    ports:
      - "2080:8080"
